execute:
  freeze: auto

project:
  type: website

website:
  title: "CausalTx"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

comments:
  giscus:
    repo: philipclare/CausalTx
