---
  title: "Paper 3. Butler et al. Upper limb function but not proprioception is impaired in essential tremor"
  author: "Jo Diong"
  date: "06 Jul 2023"
---

# Paper 3. Butler et al. Upper limb function but not proprioception is impaired in essential tremor.

Causal mediation analysis is a technique to estimate to what extent the causal effect of an exposure on an outcome is mediated through other paths

To do mediation analysis, plausible causal mechanisms are specified in a causal graph, and adjustments are made for potential confounding.

The analysis then partitions the average total effect of the exposure on outcome into an average effect acting through the mediator, and an average direct effect.

## Paper 3.

Fig 2 of paper shows separation of the total effect of essential tremor on physical function, into indirect effects through proprioception and tremor amplitude, and a direct effect.

In this causal structure, the 2 mediators (proprioception, tremor amplitude) are causally dependent (i.e. they are connected by an arrow)

-   When mediators are causally dependent, the average causally mediated effect (ACME) assumes interactions between the primary mediator and the outcome are independent of the exposure (i.e. causal effects of mediator on outcome don't depend on levels of exposure)

-   This assumption can't be verified using data, so

-   sensitivity analyses are performed to assess, if this assumption is violated, to what extent the ACME is prone to bias.

This study was the first application of causal mediation analysis in this field, and provided a better alternative to traditional approaches using correlations to infer causation.

## Discussion

Comments or clarifications?

-   Total effect: Between-group difference of effect of exposure on outcome

-   Average causally mediated effect (ACME): Between-group difference of effect that acts through mediator

-   Average direct effect (ADE): Between-group difference of effect that does not act through mediator

-   Average causally mediated effect in the treated (ACME treated): Between-group difference of effect, only in the treated/exposed

-   Average causally mediated effect in the control (ACME control): Between-group difference of effect, only in the controls

What is the value of ACME control?

We used R's `multimed` function in the `mediation` package; it's stable and has good documentation What other approaches or software do people use?
